### ISSUE TITLE
이더 메인넷과 충돌날수 있겠어요. replay attack 문제도 존재하네요.

### ISSUE THREAD

**Issue by trustfarm-dev** [ethersocial/ethersocial-pool#1]
이더 메인넷과 충돌날수 있겠어요. replay attack 문제도 존재하네요.
체인id 설정해야 할것 같습니다.
지금 상황이면 ETH MainNet 과 collision 날수 있어요.

**Comment by trustfarm-dev** [comment]
issues for go-esc . not, pool src.

**Comment by ethersocialcoin** [comment]
메인넷과 충돌할 우려는 없는 것으로 확인되었습니다.
