### ISSUE TITLE
영문 문서 분리

### ISSUE THREAD

**Issue by hackmod** [ethersocial/ethersocial-pool#20]
현재 한글 문서와 영문 문서가 섞여버린 형태입니다.
영문 문서를 그대로 두고, 한글 문서를 wiki쪽으로 빼는 것은 어떨까요?

그냥 기본으로 한글문서를 하고, 영문 문서는 위키로 빼거나,
이 둘을 같이 두어도 크게 상관 없을 것 같기는 합니다만..

**Comment by KIM-MYEONGHUN** [comment]
초기에 국내 마이너의 편의를 위한 사항이였으며, 건의주신 부분은 논의 후 조치하도록 하겠습니다.

**Comment by hackmod** [comment]
영문 문서로 대치되었기때문에 이슈는 닫겠습니다~
한글 문서는 위키로 옮겨주면 좋을 듯
