### ISSUE TITLE
히스토리 보존

### ISSUE THREAD

**Issue by hackmod** [ethersocial/ethersocial-pool#21]
원본 레포지터리 히스토리가 여기서도 삭제되었네요.
어려운 것은 아니니 히스토리를 그대로 보존하게끔 하는 것은 어떨까요?

**Comment by akx20000a** [comment]
$ git remote add sammy https://github.com/sammy007/open-ethereum-pool
	$ git fetch sammy
	$ git merge --allow-unrelated-histories sammy007/master

이 정도?

**Comment by hackmod** [comment]
`"--allow-unrelated-histories"` 옵션이 뭔가 했더니 git 최신에서 지원하나보죠? 자동화된 툴은 장단점이 있으니..

**Comment by akx20000a** [comment]
@hackmod 네 그럼에도 커밋간의 연동이 되지 않는 단점이 존재합니다.
결국 다시 클론,,,,

**Comment by kimmyeonghun** [comment]
develop 레포지토리 히스토리 복원
